language: clojure
lein: 2.8.1
install:
  # Get recent node:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
before_script:
  - npm install -g eclint
  - eclint check .* * src/**/*.clj test/**/*.clj
  - lein install
  - lein cljfmt check
script:
  - travis_wait lein with-profile +dev cloverage --coveralls
after_success:
  - curl -F 'json_file=@target/coverage/coveralls.json' 'https://coveralls.io/api/v1/jobs'
jdk:
  - oraclejdk8
  - oraclejdk11
